version: 2
jobs:
  build_docker:
    docker:
      - image: circleci/node 
    working_directory: ~/zokrates
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - run: ./scripts/build.sh
  build_npmjs:
    docker:
      - image: circleci/node 
    working_directory: ~/zokrates
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - run: ./scripts/publish.sh
workflows:
  version: 2
  build:
    jobs:
      - build_docker:
          context: zokrates
          filters:
            branches:
              only: 
              - master
      - build_npmjs:
          context: zokrates
          filters:
            branches:
              only: 
              - master