version: 2
jobs:
  build:
    docker:
      - image: blockchainit/rust-wasm-env:latest
    working_directory: ~/zokrates-js
    steps:
      - checkout
      - run:
          name: Generate cargo lockfile          command: npm run build

          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run: 
          name: Run build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
