version: 2
jobs:
  build:
    docker:
      - image: circleci/node 
    working_directory: ~/zokrates-js-node
    steps:
      - checkout
      - setup_remote_docker
      - run: ./scripts/build_docker.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: zokrates
          filters:
            branches:
              only: master